services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/myapp
    command: sh -c "npx prisma generate && npx prisma db push && npm start"
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=myapp
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data: